sudo: false
language: python
matrix:
  include:
    - os: linux
      python: 2.7
      env: TOX_ENV=py27
    - os: linux
      python: 3.3
      env: TOX_ENV=py33
    - os: linux
      python: 3.4
      env: TOX_ENV=py34
    - os: linux
      python: 3.5
      env: TOX_ENV=py35
    - os: linux
      python: pypy
      env: TOX_ENV=pypy
    - os: osx
      language: generic
      env: TOX_ENV=py27
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
install:
  - pip install tox
script: tox -e $TOX_ENV
